# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Robot_controller

  Robot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - 6RJ1
      - 6RJ2
      - 6RJ3
      - 6RJ4
      - 6RJ5
      - 6RJ6